services:
  mysql:
    image: mysql:8.0.43
    restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
      - ./initdb:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -p${MYSQL_ROOT_PASSWORD} || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 30
      start_period: 20s

  backend:
    image: paymybuddy-backend:v1
    restart: always
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      SPRING_APPLICATION_JSON: >
        {
          "server.port": ${SERVER_PORT},
          "spring.datasource.url": "${SPRING_DATASOURCE_URL}",
          "spring.datasource.username": "${SPRING_DATASOURCE_USERNAME}",
          "spring.datasource.password": "${SPRING_DATASOURCE_PASSWORD}",
          "spring.jpa.database-platform": "org.hibernate.dialect.MySQL8Dialect"
        }

volumes:
  db_data:
